spring:
  profiles:
    active: develope
    
book-search-server:
  kakao:
    url: https://dapi.kakao.com/v3/search/book
    appKey: 163400af51d05613201fa978eed3e51f
  naver:
    url: https://openapi.naver.com/v1/search/book.json
    clientId: PhErPrN5izYtS3vzPCSO
    clientSecret: nYgkVqH8ed

---
spring:
  profiles: develope
  thymeleaf:
    cache: false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

---
spring:
  profiles: production
